// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh2IZ1N8XfnPKugTF5ANwQnhZRpl-Lc5Q',
    appId: '1:936622727644:web:fa424ebf381cf72a0aef19',
    messagingSenderId: '936622727644',
    projectId: 'talkin-app-talkin',
    authDomain: 'talkin-app-talkin.firebaseapp.com',
    storageBucket: 'talkin-app-talkin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrE6QAC7Uhwww8rhx1KcOu2VhMWeEO18',
    appId: '1:936622727644:android:2af3509e3dcf74700aef19',
    messagingSenderId: '936622727644',
    projectId: 'talkin-app-talkin',
    storageBucket: 'talkin-app-talkin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbGVEUoLeza_hAkxVZQ9ItwSSVGXL3Cqg',
    appId: '1:936622727644:ios:1408b587fd8246c30aef19',
    messagingSenderId: '936622727644',
    projectId: 'talkin-app-talkin',
    storageBucket: 'talkin-app-talkin.firebasestorage.app',
    iosBundleId: 'com.incodes.talkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbGVEUoLeza_hAkxVZQ9ItwSSVGXL3Cqg',
    appId: '1:936622727644:ios:1408b587fd8246c30aef19',
    messagingSenderId: '936622727644',
    projectId: 'talkin-app-talkin',
    storageBucket: 'talkin-app-talkin.firebasestorage.app',
    iosBundleId: 'com.incodes.talkin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh2IZ1N8XfnPKugTF5ANwQnhZRpl-Lc5Q',
    appId: '1:936622727644:web:02ae89681e0212940aef19',
    messagingSenderId: '936622727644',
    projectId: 'talkin-app-talkin',
    authDomain: 'talkin-app-talkin.firebaseapp.com',
    storageBucket: 'talkin-app-talkin.firebasestorage.app',
  );
}
